### ISSUE TITLE
[Rule Tuning] MacOS_Cryptominer_Generic_333129b

### ISSUE THREAD

**Issue by krypt0x** [elastic/protections-artifacts#12]
## Impacted Rule: MacOS_Cryptominer_Generic
Rule Name with ID: MacOS_Cryptominer_Generic_333129b

## Description
This crypto wallet has been wrongly flagged as malicious from some time now. It's definitely a false positive. Could you please have a look at it?
https://github.com/ConcealNetwork/conceal-desktop

## Example Sample
https://www.virustotal.com/gui/file/65aa9266c675e9e9ed55d4eb315a7a27804c24329c6ed7c908c504403317b12d/detection

**Comment by terrancedejesus** [comment]
Hello @krypt0x - Thank you for taking the time to bring this to our attention. After further review, we have collectively decided to deprecate this rule due to, as you mentioned, the false-positive alerts we have been tracking globally. An update for this deprecation should be released sometime this week. We will close this issue in the meantime, but if you have any further questions please feel free to let us know.

Thanks again for being a community member and contributor!
